name: TypeScript Types Check

on: [push, pull_request]

jobs:
  typescript-types-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Preparing GitHub Action
        uses: actions/checkout@v2
      - name: Preparing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Yarn
        run: npm install -g yarn
      - name: Installing dependencies
        run: yarn
      - name: Checking TypeScript Types
        run: yarn check-types
